id: P508E53E5
initial_creation_type: input
source_metadata:
  Title: Cittavisuddhiprakarna of Aryadeva
  Editor: Patel, Prabhubhai Bhikhabhai
  Publisher: Visva-Bharati
  Place of Publication: Nagpur
  Year: '1949'
  Cittaviśuddhiprakaraṇa:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Milan Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:58:32.330317'
last_modified_at: '2022-03-08T16:58:32.330325'
